"""Model diagnostics: importance sampling weights and PSIS."""

from jax import vmap
from numpyro.infer.util import log_density

__all__ = ["compute_importance_weights"]


def compute_importance_weights(
    model,
    guide,
    samples: dict,
    params: dict | None = None,
    model_args=(),
    model_kwargs=None,
):
    """Given the model and the guide, return the log of the IS weights.

    For each sample \u03b8_s from the guide (proposal distribution), estimates
    the log of the joint probability log p(\u03b8_s, y), where \u03b8 are the samples
    and y is the data, along side with log q(\u03b8_s), then returns `log p - log q`.

    Parameters
    ----------
    model: callable
        Python callable with `numpyro.sample` primitives
    guide: callable
        Python callable with `numpyro.sample` and `numpyro.param` primitives.
        If an autoguide object, must be seeded.
    samples: dict
        Samples *from the guide*. For example, for autoguides, that expose
        `sample_posterior` method, samples can be generated by calling
        `guide.sample_posterior(rng_key, params, sample_shape=(num_sample,))`.
    params: dict, optional
        Values of the guide parameters to be substituted when evaluating the
        guide's probability density.
    model_args, model_kwargs: tuple and dict respectively
        Arguments to be passed to both the model and the guide when evaluating
        the probability density.

    Returns
    -------
    log_weights: Float[Array, " num_sample"]
        Array of importance sampling weights for each passed sample.
        Can be further passed to `arviz.stats.stats.psislw`, but must be converted
        to a numpy array first. (Then optionally to an `xr.DataArray` with an axis
        named `__sample__`.)

    """
    if params is None:
        params = {}
    if model_kwargs is None:
        model_kwargs = {}

    log_density_model = vmap(
        lambda sample: log_density(model, model_args, model_kwargs, params=sample)[0],
        in_axes=0,  # map over samples
    )(samples)

    # consider checking if the guide is seeded and if not,
    # at least notify the user if not seed it yourself
    log_density_guide = vmap(
        lambda sample: log_density(
            guide, model_args, model_kwargs, params=sample | params
        )[0],
        in_axes=0,  # map over samples
    )(samples)
    return log_density_model - log_density_guide


# def _gpdfit(ary: jnp.ndarray) -> tuple:
#     """Estimate the GPD shape (k) and scale (sigma) parameters."""
#     prior_bs = 3.0
#     prior_k = 10.0
#     n = ary.shape[0]
#     m_est = 30 + int(np.sqrt(n))

#     # build b_ary
#     i = jnp.arange(1, m_est + 1, dtype=float)
#     b_ary = 1 - jnp.sqrt(m_est / (i - 0.5))
#     b_ary = b_ary / (prior_bs * ary[jnp.floor(n / 4 + 0.5).astype(int) - 1])
#     b_ary = b_ary + 1 / ary[-1]

#     # compute k_ary
#     # b_ary[:, None] * ary -> broadcast shape (m_est, n)
#     k_ary = jnp.log1p(-b_ary[:, None] * ary).mean(axis=1)
#     len_scale = n * (jnp.log(-(b_ary / k_ary)) - k_ary - 1)
#     # weights
#     weights = jnp.exp(-(len_scale - len_scale[:, None]))
#     weights = weights.sum(axis=1)
#     weights = 1 / weights

#     # prune near-zero weights
#     eps = jnp.finfo(float).eps
#     mask = weights >= 10 * eps
#     weights = weights[mask]
#     b_ary = b_ary[mask]

#     # normalize
#     weights = weights / jnp.sum(weights)

#     # posterior mean for b
#     b_post = jnp.sum(b_ary * weights)
#     k_post = jnp.log1p(-b_post * ary).mean()
#     sigma = -k_post / b_post
#     k_post = (n * k_post + prior_k * 0.5) / (n + prior_k)
#     return k_post, sigma


# def _gpinv(probs: jnp.ndarray, kappa: float, sigma: float) -> jnp.ndarray:
#     """Inverse CDF of the Generalized Pareto distribution."""
#     x = jnp.full_like(probs, jnp.nan)
#     if sigma <= 0:
#         return x
#     # valid slice
#     ok = (probs > 0) & (probs < 1)

#     def _compute(val):
#         p = val
#         return lax.cond(
#             jnp.abs(kappa) < jnp.finfo(float).eps,
#             lambda pr: -jnp.log1p(-pr),
#             lambda pr: jnp.expm1(-kappa * jnp.log1p(-pr)) / kappa,
#             p,
#         )
#     # compute for ok
#     x = x.at[ok].set(_compute(probs[ok]) * sigma)
#     # handle boundaries
#     x = x.at[probs == 0].set(0.0)
#     x = x.at[probs == 1].set(jnp.where(kappa >= 0, jnp.inf, -sigma / kappa))
#     return x


# def _psislw(log_weights: jnp.ndarray,
#             cutoff_ind: int,
#             cutoffmin: float = -jnp.inf,
#             normalize: bool = True) -> tuple:
#     """Pareto smoothed importance sampling for 1D log-weights."""
#     x = log_weights.astype(float)
#     max_x = jnp.max(x)
#     x = x - max_x

#     # sort
#     ind = jnp.argsort(x)
#     # cutoff
#     xcutoff = jnp.maximum(x[ind[cutoff_ind]], cutoffmin)
#     exp_xcut = jnp.exp(xcutoff)

#     tail_mask = x > xcutoff
#     tailinds = jnp.where(tail_mask)[0]
#     tail_len = tailinds.shape[0]

#     def no_smooth():
#         return jnp.inf, x

#     def do_smooth():
#         x_tail = x[tailinds]
#         si = jnp.argsort(x_tail)
#         # fit
#         k, sigma = _gpdfit(jnp.exp(x_tail) - exp_xcut)
#         def smooth_branch(args):
#             k_val, sigma_val = args
#             # ordered probs
#             sti = jnp.arange(0.5, tail_len) / tail_len
#             st = _gpinv(sti, k_val, sigma_val)
#             st = jnp.log(st + exp_xcut)
#             # insert
#             x_new = x.at[tailinds[si]].set(st)
#             x_new = jnp.where(x_new > 0, 0.0, x_new)
#             return k_val, x_new
# n
#         return lax.cond(jnp.isfinite(k), smooth_branch, lambda _: (k, x), (k, sigma))

#     k, x = lax.cond(tail_len <= 4, lambda: no_smooth(), do_smooth, operand=None)

#     # renormalize or re-add max
#     if normalize:
#         # logsumexp
#         mx = jnp.max(x)
#         lse = mx + jnp.log(jnp.sum(jnp.exp(x - mx)))
#         x = x - lse
#     else:
#         x = x + max_x
#     return x, k
